Asignment4-BlancaRodrigo
FacultadInformatica-LinkedData/Curso2020-2021-ODKG pull request #149
Opened 2020-10-02 11:33 UTC by brodrigol

2020-10-02 13:05 UTC, dachafra requested changes
task06: awesome, perfect!
task07: you need to think a bit more, remember that if X is subclassOf Y and Y subclassOf Z, implicitly X is also subclassOf Z, the results of your queries are not complete ;-)
task08: awesome! perfect!

2020-10-03 09:57 UTC, brodrigol commented
Hi David,
could you also look at task 9? I uploaded it the first time but I don't know if you saw it.
Thank you.

2020-10-03 11:56 UTC, dachafra commented
awesome Blanca! @brodrigol 
good work :-D

2020-10-03 11:57 UTC, dachafra approved these changes

2020-10-03 11:57 UTC, merged