assignment 4 mandatory
FacultadInformatica-LinkedData/Curso2020-2021-ODKG pull request #151
Opened 2020-10-02 14:56 UTC by Rafata8

2020-10-02 15:36 UTC, dachafra requested changes
task06: perfect
task07: review the RDFlib queries, the results have to be the same as the ones made in SPARQL

2020-10-04 17:57 UTC, Rafata8 commented
I have already fixed the errors, i think that everything is fine now

2020-10-04 18:09 UTC, dachafra approved these changes

2020-10-04 18:10 UTC, dachafra commented
awesome @Rafata8 !

2020-10-04 18:10 UTC, merged