Assigment 4; task 6 and 7
FacultadInformatica-LinkedData/Curso2020-2021-ODKG pull request #195
Opened 2020-10-05 20:19 UTC by angeel2706

2020-10-06 07:58 UTC, dachafra requested changes
task 6 ok
task7: results are not complete and you have to do the queries ALSO in SPARQL

2020-10-06 07:59 UTC, dachafra commented
this PR also contains assignment 2 and 3 @ocorcho

2020-10-06 08:43 UTC, ocorcho requested changes
Errors in Assignment 2a, and assignment 3 has also errors in queries 4 and 5.

2020-10-06 08:43 UTC, ocorcho commented on Assignment2/angeel2706.ttl
> +Measurement 8401: hasTemperature: "29";
Wrong syntax.

2020-10-08 13:51 UTC, ocorcho commented
Closing this since the original repository has been deleted.

2020-10-08 13:51 UTC, closed without merging