Assignment 6 - Group 09
FacultadInformatica-LinkedData/Curso2020-2021-ODKG pull request #265
Opened 2020-11-11 19:22 UTC by agouloumis

2020-11-11 19:26 UTC, agouloumis commented
Only take into account the last commits for assignment 6. The other commits are already in another pull request named "Group 09 Assignment 5", in https://github.com/FacultadInformatica-LinkedData/Curso2020-2021-ODKG/pull/257

Sorry for the inconvenience.

2020-11-13 15:34 UTC, ocorcho requested changes

2020-11-13 15:34 UTC, ocorcho commented on HandsOn/Group09/mappings/contratos-with-links.yml
> +  db: https://es.dbpedia.org/page/
No es /page/ sino /resource/

2020-11-13 15:34 UTC, ocorcho commented on HandsOn/Group09/mappings/contratos-with-links.yml
> +#      - [org:subOrganizationOf, db:Ayuntamiento_de_Madrid]
It seems to be ok.

2020-11-13 15:34 UTC, ocorcho commented on HandsOn/Group09/mappings/contratos-with-links.yml
> +    s: :/department/$(Section_IRI)/contracting_body/$(Contracting_Body_IRI)
REmove department and section IRI

2020-11-13 15:57 UTC, ocorcho commented
Good usage of the PPROC ontology, with only very minor errors. Links are ok as well, although we understand the difficulty of finding too many links in this context. 
You obtain a grade of 10 over 10 in this part of the evaluation

2020-11-19 17:40 UTC, agouloumis commented
Errors solved :-)

2020-11-20 16:12 UTC, merged