Create ThomasVanDommelen.ttl
FacultadInformatica-LinkedData/Curso2020-2021-ODKG pull request #83
Opened 2020-09-27 11:45 UTC by papadragon66

2020-09-27 11:59 UTC, ocorcho requested changes

2020-09-27 11:59 UTC, ocorcho commented on Assignment2/ThomasVanDommelen.ttl
> +:Measurement8401  :hasTemperature :29;
There are syntactic errors here in the representation of literals. And be careful as well and provide datatypes for them. Check what other students have done.

2020-09-29 10:30 UTC, ocorcho requested changes

2020-09-29 10:30 UTC, ocorcho commented on Assignment2/ThomasVanDommelen.ttl
> +:Measurement8401  :hasTemperature :29;
Please check what other students have done.

2020-09-29 10:39 UTC, papadragon66 reviewed
changed

2020-09-29 13:39 UTC, merged